POLDER-Crew/polder-federated-search

app/search/dataone.py, app/search/gleaner.py, app/search/search.py, app/static/css/_search.scss, app/templates/results.html, app/tests/test_search.py, docker/docker-compose.yaml, docker/gleaner.yaml, helm/Chart.yaml, helm/templates/gleaner-config.yaml, package.json
- get and expose urls from more places in DataONE results (https://trello.com/c/oS4utan7)
- find and expose DOIs more prominently (https://trello.com/c/Cj3TbC3U)
- Remove NPDC from the list of Gleaner repositories to crawl, because it's already covered by DataONE
=> Bug fixes for URLS and DOIs

helm/templates/crawl.yaml
For https://trello.com/c/2gae85vy
I noticed today that the weekly 'crawl' job was failing on search-dev, and it was failing because it couldn't do `curl https://schema.org/version/latest/schemaorg-current-https.jsonld`.
The fix is to tell the job where it can find a DNS server. There's one specified in `gleaner-deployment.yaml`, so I must have just forgotten to put this in the crawl configuration too.
=> Add a DNS policy so this job knows how to get to the url we want to curl

LICENSE, helm/Chart.yaml, package.json
It's official! We have a license, and now we can use it.
For https://trello.com/c/cxBJRBkq
=> Apply BSD license

README.md, helm/Chart.yaml, helm/templates/web-deployment.yaml, package.json
It gets the Sentry endpoint URL from a `secrets` file now, to make it easier to expose it to the Helm deployment.
=> A better way to set up Sentry error reporting

app/routes.py, app/search/dataone.py, app/search/gleaner.py, app/templates/404.html, app/tests/search/test_gleaner.py
- Don't overwhelm Sentry by logging 404s in it
- Make a real 404 page and route 404s to it
- Python logging library uses the old-style syntax
- Slightly better query input sanitization
=> Better error handling

app/__init__.py, app/app_config.cfg, app/routes.py, docker/docker-compose.yaml, helm/templates/web-deployment.yaml, helm/values-dev.yaml, helm/values-local.yaml, helm/values-prod.yaml, requirements.txt
This solves a couple of problems:
- By logging 404s, I was creating a lot of noise in our error reporting software and causing it to go over its quota. I hadn't realized that `logger.error` would log a separate entry from `capture_exception`. So all the 404s were being logged in there and any legitimate errors were being logged *twice* (https://trello.com/c/qD75aDZs)
- 
- I can now filter between 'dev', 'production', and 'local' in there more easily (https://trello.com/c/XNZPY3UP)
I think we have to start paying for it if I invite you, annoyingly, so this is a good one to get into LastPass.
=> Be less aggressive about logging 404s, distinguish sentry environments

README.md, build-sitemap/index-gcmd.py, docker/docker-compose.yaml, docker/index-gcmd.py, helm/templates/setup-gleaner.yaml
Also, I noticed that the URL for building the GCMD sitemap was likely leaving some repositories out because the beginning of the URL was repeated, so I fixed that.
=> Documentation update for GCMD

helm/values-dev.yaml, helm/values-prod.yaml
Today, @yemoski noticed that some search-dev queries were failing. This was because GraphDB was running out of memory for large result sets, and bailing out.
I noticed that we have the maximum heap size for GraphDB set to 2GB, but the documentation recommends a maximum of 6GB: https://graphdb.ontotext.com/documentation/10.0/configuring-a-repository.html#configure-graphdb-memory
Hopefully this will help.
=> Bump up GraphDB heap size to the recommended amount

app/templates/results.html, docker/docker-compose.yaml, helm/Chart.yaml, package.json
When I was developing the map locally, I didn't have a Gleaner index built, so I was only getting DataONE results. When I deployed it to search-dev, suddenly I had results with no geometries, and Javascript errors to go with them.
=> Do not try to show geometries that do not exist, bump version

app/__init__.py, app/app_config.cfg, app/routes.py, app/templates/base.html, dev.env, helm/templates/web-deployment.yaml, helm/values-dev.yaml, helm/values-local.yaml, helm/values-prod.yaml, requirements.txt
I don't normally like to pile multiple fixes into one branch, but here we are. This has:
- an upgrade to the Sentry Python API
- Better handling for 405 errors, because people are using bots to try weird stuff on our server and it's clogging up our error reporting system with junk
- A way to set the Google Analytics IDs as an environment variable, so that we can set different IDs per-deployment, using Helm
=> Sentry and Google Analytics

app/search/gleaner.py, app/static/css/_constants.scss, app/static/css/_elements.scss, app/static/css/_form.scss, app/static/css/_map.scss, app/static/css/_nav.scss, app/static/css/_results.scss, app/static/js/map.js, app/static/js/search.js, app/static/maps/README.md, app/templates/base.html, app/templates/index.html, app/templates/partials/date-picker.html, app/templates/partials/map.html, app/templates/results.html, docker/docker-compose.yaml, helm/Chart.yaml, helm/templates/recreate-index.yaml, helm/templates/setup-gleaner.yaml, package.json
This change:
- tightens up mobile styles for small screens, including on the map
- Makes the map appear below the paginator when it is displayed for search results
- Prepares the map to be initialized for reasons other than displaying search results (maybe there will be two map areas in practice, one for people to draw on for spatial search and one to show results, not sure)
- Makes the loading spinner take up the whole page so it looks less like the page jumps around when searching / paging
- Changes the date search labels to hopefully make more sense
- Adds a description for screenreaders to the maps
=> Mostly map touchups

app/search/gleaner.py, docker/docker-compose.yaml, helm/Chart.yaml, helm/values-dev.yaml, helm/values-prod.yaml, package.json
This can at least make what's on search-dev shippable to production.
What I found was two things:
- `?catalog ?relationship ?s . ` is by far the most expensive thing in that query - it takes the most time, by orders of magnitude, so I changed things around so that it is called fewer times.
- `FILTER( CONTAINS(?author, '''{author}''')) .` was taking a long time because `?author` is optional. Changing it to `FILTER(BOUND(?author) && CONTAINS(?author, '''{author}''')) .` to check whether `?author` even exists first helped.
Check whether ?author is bound and minimize calls for an expensive statement
=> A step toward speeding up sparql queries

docker/lucene-connector.sparql, helm/templates/crawl.yaml, helm/templates/recreate-index.yaml, helm/templates/setup-gleaner.yaml
- Enable faceted indexing / searching in Lucene connector config
- Revert to an earlier version of minio-client in Helm charts because it includes curl (we are using that)
=> Faceted indexing

app/routes.py, app/tests/test_routes.py, requirements.txt
People are doing fun stuff like searching for `&&/bin/cat%20/etc/passwd` and page number `%SYSTEMROOT%\\win.ini`, so now we can handle that a little more gracefully.
=> Update the Sentry API and handle a few of this weeks errors

app/search/gleaner.py, app/tests/search/test_gleaner.py, docker/gleaner.yaml, docker/lucene-connector.sparql
I figured out how to make full-text index look at the right attributes to search for just authors, instead of doing it in SPARQL, which will make author searches much faster.
This will also let us do stuff like `luc:query '''keywords:ice''' ;` and it'll Just Work Like That, which is pretty cool, I think.
=> Enable Lucene text searches for author and license, via faceting

app/search/gleaner.py, app/templates/base.html, app/templates/results.html, app/tests/search/test_gleaner.py
- There was an error message due to the fact that `resultGeometries` was getting declared when it was already defined
- Someone used GeoShape: circle (causing https://trello.com/c/hBuCTrUh)
- the values for `data-score` should have quotes around them
=> Fix a little grab bag of front-end bugs

README.md, docker/docker-compose.yaml, helm/Chart.yaml, helm/templates/crawl.yaml, helm/templates/gleaner-deployment.yaml, helm/templates/recreate-index.yaml, helm/templates/setup-gleaner.yaml, helm/values-dev.yaml, helm/values-local.yaml, helm/values-prod.yaml, package.json
For https://trello.com/c/o3ccHYtp and https://trello.com/c/524m7c6P 
- fixing a bug that happens when we re-crawl / reindex
- staggering the development and production crawl cycles
- adding some documentation
- Using an official GraphDB image instead of one we built ourselves (when this goes to production the [graphdb-docker](https://github.com/WDS-ITO/graphdb-docker) repo will be able to be deleted and so will its associated Docker images)
=> Indexing and triplestore fixes

app/search/gleaner.py, build-sitemap/build-sitemaps.sh, docker/build-ccadi-sitemap.sh, docker/docker-compose.yaml, docker/gleaner.yaml, helm/Chart.yaml, helm/templates/gleaner-config.yaml, helm/templates/setup-gleaner.yaml, package.json
https://trello.com/c/xxtod30P
An ideal solution for this would be something like I outline in  https://trello.com/c/3hYsa6iE, where you could give an API endpoint template URL to Gleaner, and it would page through the API in an automated way and ingest the JSON-LD that it can get there.
But for now, we can index CCADI by asking Gleaner to crawl its API endpoint, by building a sitemap that pages through it.
I had to slightly modify the SPARQL query that we use in order to get CCADI search results to show up, but otherwise I could just plug it into our system, which says great things about the CCADI developers.
=> Proof of concept: index CCADI

app/templates/help.html
These were the changes suggested by CJ;
-'ice~'  ->  Stating the examples of words similar to ice spelling is
- 'green^4 ice' -> Stating what happens when 'green' relevance is boosted, 'green' becomes prioritized.
- '+green ice' -> breaking down what both terms are into 'green ice' 
- Also, He suggested we use 'search results' instead of 'documents' because the users may not only get PDFs.
=> some word changes

docker/docker-compose.yaml, docker/lucene-connector.sparql, helm/templates/gleaner-deployment.yaml
For https://trello.com/c/lRGMaOyz
The problem was basically that we were telling the full-text search in GraphDB to index every single field literal, regardless of its type, and then it was trying to look for text that had words in a certain order in a `boolean` field. Which isn't going to happen.
The fix is to explicitly tell the full-text search connector which fields it should index. I also updated the GraphDB Docker image while I was in here, because they made a few security fixes.
=> SPARQL full text search error

helm/templates/setup-gleaner.yaml
This makes our upgrade work better, during deployments.
=> Set a TTL for helm jobs to live

docker/docker-compose.yaml, docker/gleaner.yaml, helm/templates/crawl.yaml, helm/templates/gleaner-config.yaml, helm/templates/gleaner-deployment.yaml, helm/templates/recreate-index.yaml, helm/templates/setup-gleaner.yaml
For https://trello.com/c/3hYsa6iE - the Gleaner changes to support this have been officially released, so we can deploy them now!
I updated some other images to the latest while I was at it.
=> Move to new CCADI API crawl method and update other Docker images

deployment-support/graphdb/write-to-triplestore.sh, docker/docker-compose.yaml, helm/templates/_helpers.tpl, helm/templates/gleaner-deployment.yaml
A couple scripts didn't work as I thought they did, particularly around specifying where the Minio service is listening, and hard-coding the bucket that RDF triples get stored in.
=> Follow-on fixes for #121

app/routes.py, app/search/dataone.py, app/search/gleaner.py, app/tests/search/test_dataone.py, deployment-support/gleaner/docker.yaml, docker/docker-compose.yaml, helm/Chart.yaml, helm/templates/_helpers.tpl, helm/templates/gleaner-config.yaml, helm/templates/gleaner-deployment.yaml, helm/templates/setup-gleaner.yaml, package.json
The main change here is that we got some invalid ISO dates and it made the site crash, so this guards against that. Also, later versions of Chrome headless are causing problems with the Gleaner toolchain, so I pinned the version of that image to a specific version.
=> A fix for a date bug, pinning Docker image versions
