- .gitignore
- README.md
- helm/Chart.yaml
- helm/templates/example.secrets.yaml
- helm/templates/s3system-service.yaml
- helm/values.yaml
Necessary changes to work in Dataone's k8s environment
> Dataone deploy

- Dockerfile
- app/templates/base.html
- app/templates/index.html
- docker/docker-compose.yaml
- docker/gleaner.yaml
- helm/Chart.yaml
- helm/templates/web-deployment.yaml
- helm/values.yaml
Needed to be able to run at https://api.test.dataone.org/polder/ , which is where this is supposed to go for the time being.
> Run in subdirectory

- app/routes.py
- app/search/dataone.py
- app/search/gleaner.py
- app/search/search.py
- app/static/css/_constants.scss
- app/static/css/_nav.scss
- app/static/css/_search.scss
- app/templates/base.html
- app/templates/results.html
- app/templates/search.html
- app/tests/test_search.py
- docker/gleaner.yaml
- docker/write-to-triplestore.sh
- helm/Chart.yaml
- package.json
- yarn.lock
- normalize scores across searches in a naive way
- Add a SearchResult class to have uniform objects to present in the UI
- Remove some duplicates from the Gleaner search
- expose DOIs more often as links to get the data
- show keywords in search results
- nicer styling
> Results deduping and sorting

- app/search/gleaner.py
- app/templates/results.html
Fix for https://trello.com/c/2cv9MMzG and a partial fix for https://trello.com/c/oS4utan7
> Gem query and URL bug fixes

- app/search/dataone.py
- app/tests/search/test_dataone.py
For https://trello.com/c/CmVKZvrg, which was pointed out by Matt Jones.
> Fix data one urls

- app/search/gleaner.py
- docker/docker-compose.yaml
- helm/Chart.yaml
- package.json
Not using UNION: the query took more than a minute. Using UNION: 2 or 3 seconds, on my underpowered dev machine.
> Get richer g-e-m results and speed up query

- app/routes.py
- app/tests/search/test_gleaner.py
- app/tests/test_routes.py
- docker/docker-compose.yaml
- helm/Chart.yaml
- helm/templates/web-deployment.yaml
- helm/values.yaml
- package.json
For https://trello.com/c/v3cUYATl
> Stop serving in subdirectory /polder but make it so that path still works

- app/__init__.py
- app/routes.py
- app/search/dataone.py
- app/search/gleaner.py
- app/search/search.py
- app/static/css/_nav.scss
- app/static/css/_results.scss
- app/static/css/paginator.scss
- app/static/css/style.scss
- app/static/js/search.js
- app/template_helpers.py
- app/templates/base.html
- app/templates/partials/paginator.html
- app/templates/results.html
- app/templates/search.html
- app/tests/search/test_dataone.py
- app/tests/search/test_gleaner.py
- app/tests/search/test_search_result_set.py
- app/tests/test_routes.py
- docker/docker-compose.yaml
- docker/gleaner.yaml
- helm/Chart.yaml
- helm/templates/gleaner-config.yaml
- package.json
- yarn.lock
Now you can get to all of your search results. https://trello.com/c/0yIuIFxE
Includes small fix for the no-js templates while I was in there: https://trello.com/c/eWhOE6Jb
Also removes USAP-DC from Gleaner indexing, since DataONE is including them already.
> Pagination!

- app/__init__.py
- app/routes.py
- app/static/css/_errors.scss
- app/static/css/_results.scss
- app/static/css/style.scss
- app/static/js/search.js
- app/templates/500_generic.html
- app/templates/results.html
- app/templates/search.html
- dev.env
- helm/templates/web-deployment.yaml
- requirements.txt
- Add a nicer user experience for when there are no search results available
- Add integration with sentry.io to record information about errors on the server that users might hit
- Add a nicer user experience for when an unknown error occurs
For https://trello.com/c/R7IDgdK2
> Better error handling in results and elsewhere

- helm/templates/gleaner-deployment.yaml
- helm/templates/setup-gleaner.yaml
Based on https://github.com/NCEAS/metadig-engine/commit/1c00aeccf84593b031d449ffcb7d72e8457ffeb4 
Long-term, I'd like to get more up to date docker images and remove these config blocks. I've opened a Trello item to do that.
> Add a DNS Policy to configs with images based on older versions of alpine

- app/static/css/_results.scss
- app/templates/partials/paginator.html
For https://trello.com/c/4u8j8OBU which just makes me look like a hillbilly
> Hide the paginator UI for just one page of results

- docker/clear-triplestore.sh
- docker/docker-compose.yaml
- docker/write-to-triplestore.sh
- helm/Chart.yaml
- helm/templates/_helpers.tpl
- helm/templates/crawl.yaml
- helm/templates/gleaner-deployment.yaml
- helm/templates/recreate-index.yaml
- helm/templates/setup-gleaner.yaml
- helm/values-dev.yaml
- helm/values-local.yaml
- helm/values-prod.yaml
- package.json
For https://trello.com/c/hbBiR00g and https://trello.com/c/LIiijZ9m
> Image updates

- app/static/css/_form.scss
The loading text and spinner is centered on all screens
> the loading button has been centered

- app/routes.py
- app/static/css/_nav.scss
- Better logging for errors / exceptions, and not sending them to Sentry if we aren't in a production environment
- I felt like the menu would look better left-aligned on large screen sizes and centered on small ones
> Debug logging, menu alignment

- app/search/gleaner.py
- app/search/search.py
- app/templates/results.html
Added the license field to full abstract text in our search results
> Added the license field in the search result

- app/search/gleaner.py
- app/tests/search/test_gleaner.py
- requirements.txt
- yarn.lock
I'll explain what stuff does in some comments in the diff view.
For https://trello.com/c/HNG1vnyQ
> Get our SPARQL query to pick up CCHDO results

- app/search/search.py
- app/static/css/_results.scss
- app/static/js/search.js
- app/templates/results.html
the show more button is not meant to show only if the text is already truncated (less than 500 words), but it does not show at all. if I remove the if  condition on line 30 in search.js, it works perfectly. I was wondering if you know why this is happening?
maybe it is counting the white spaces (but i usewd the trim function to remove it), not sure why that is happening?
> show more button added

- app/search/dataone.py
- app/search/search.py
- app/static/css/_results.scss
- app/static/js/search.js
- app/templates/results.html
- docker/bas-sitemap.xml
Author name and timespan  in the "show more content"
> button now on a new line

- app/search/dataone.py
- app/search/search.py
- app/templates/results.html
- app/tests/search/test_dataone.py
- app/tests/search/test_search_result.py
i removed the data sources changes and fixed the merge conflict in this branch
> conflict fixed

- README.md
- app/search/dataone.py
- app/search/gleaner.py
- app/tests/search/test_dataone.py
- app/tests/search/test_gleaner.py
- dev.env
- docker/bas-sitemap.xml
- docker/clear-triplestore.sh
- docker/docker-compose.yaml
- docker/geosparql.sparql
- docker/gleaner.yaml
- docker/lucene-connector.sparql
- docker/polder.ttl
- docker/write-to-triplestore.sh
- helm/Chart.yaml
- helm/templates/_helpers.tpl
- helm/templates/crawl.yaml
- helm/templates/gleaner-config.yaml
- helm/templates/gleaner-deployment.yaml
- helm/templates/polder-repo-config.yaml
- helm/templates/recreate-index.yaml
- helm/templates/setup-gleaner.yaml
- helm/templates/web-deployment.yaml
- helm/values-dev.yaml
- helm/values-local.yaml
- helm/values-prod.yaml
- package.json
For https://trello.com/c/He61g5dr and https://trello.com/c/KjVMgFcQ
> Switch to using GraphDB instead of Blazegraph

- app/static/css/_results.scss
- app/templates/results.html
I removed the buttons and made each result default to full
> removed the buttons

- app/search/dataone.py
- app/search/gleaner.py
- app/search/search.py
- app/tests/search/test_gleaner.py
- package-lock.json
removed all the duplicate queries from multiple authors
> removing duplicate queries from multiple authors

- app/templates/base.html
from my research, I need this script tag running on search.polder.info for me to have google analytics reading our site.
> keys added for google analytics

- app/__init__.py
- app/helper.py
- app/routes.py
- app/search/dataone.py
- app/search/gleaner.py
- app/search/search.py
- app/static/css/_results.scss
- app/templates/results.html
- app/tests/search/test_dataone.py
I wrote the base code to get the original sources for dataone into a dictionary for 120 seconds.
I was hoping to get a review on the caching of the dictionary. Thanks!
> Caching original dataone sources

- app/search/gleaner.py
- docker/docker-compose.yaml
- helm/Chart.yaml
- package.json
Walking back a few changes I made that did speed things up - but left out some query results.
> Some query behavior fixes

- README.md
- package.json
I'll make corresponding changes in the doc book repo too.
> Update code repo link for new github organization

- docker/docker-compose.yaml
For https://trello.com/c/53cKcIZe - NCPOR saw this error in their setup process.
> Fix the environment variables in the sitemap builder script

- .gitignore
- build-sitemap/Dockerfile
- build-sitemap/build-sitemaps.sh
- build-sitemap/index-datastream.py
- build-sitemap/index-gcmd.py
- build-sitemap/sitemap_utils.py
- docker/docker-compose.yaml
- docker/gleaner.yaml
- helm/Chart.yaml
- package.json
Reuses some of the GCMD sitemap-building code and factors it into a library / utils file.
> Build a sitemap for and index datastream

- helm/templates/gleaner-config.yaml
- helm/templates/gleaner-deployment.yaml
- helm/templates/setup-gleaner.yaml
- helm/values-dev.yaml
- helm/values-local.yaml
- helm/values-prod.yaml
I had some problems with weird errors during a production deploy last week, and this is what fixed it.
> Helm config tweaks

- app/search/dataone.py
- dev.env
- package.json
- yarn.lock
Work so far on the dataone side
> boosting_keywords_dataone
